require('dotenv').config();
const express=require('express'),cors=require('cors'),{authenticator}=require('otplib'),fs=require('fs'),path=require('path'),WebSocket=require('ws');
const e=express();e.use(cors());e.use(express.json({limit:'8mb'}));
const {PORT=8787,APP_KEY,ANGEL_API_KEY,ANGEL_CLIENT_CODE,ANGEL_PIN,ANGEL_TOTP_SECRET,ANGEL_CLIENT_PUBLIC_IP,ANGEL_CLIENT_LOCAL_IP='127.0.0.1',ANGEL_MAC_ADDRESS='02:00:00:00:00:01',ANTHROPIC_API_KEY,MODEL='claude-haiku-4-5-20251001',BRAVE_API_KEY}=process.env;
let angelRuntime={apiKey:ANGEL_API_KEY||'',clientCode:ANGEL_CLIENT_CODE||'',mpin:ANGEL_PIN||'',totpSecret:ANGEL_TOTP_SECRET||'',totp:''};
const A='https://apiconnect.angelone.in',WSURL='wss://smartapisocket.angelone.in/smart-stream';
const NSE_MCP_URL=process.env.NSE_MCP_URL||'https://mcp.nseindia.in/cmmkt/mcp';
let mcp={sessionId:null,protocolVersion:null,tools:[],connected:false,lastError:null,nextId:1};
const IDX={'NIFTY 50':['NSE','99926000'],'BANKNIFTY':['NSE','99926009'],'FINNIFTY':['NSE','99926037'],'MIDCPNIFTY':['NSE','99926074'],'SENSEX':['BSE','99919000']};
let sess=null,master=null,liveSocket=null,liveConnecting=false,liveWanted={},liveClients=new Set(),liveLast={};
e.use('/api',(q,s,n)=>{const key=q.get('x-app-key')||q.query.appKey;if(APP_KEY&&key!==APP_KEY)return s.status(401).json({error:'unauthorized'});n()});
const hd=x=>({'Accept':'application/json','Content-Type':'application/json','X-UserType':'USER','X-SourceID':'WEB','X-ClientLocalIP':ANGEL_CLIENT_LOCAL_IP,'X-ClientPublicIP':ANGEL_CLIENT_PUBLIC_IP||'', 'X-MACAddress':ANGEL_MAC_ADDRESS,'X-PrivateKey':angelRuntime.apiKey,...x});
async function angelJson(url,opts={}){let r=await fetch(url,{...opts,headers:hd(opts.headers||{})});const txt=await r.text();let j;try{j=JSON.parse(txt)}catch{throw Error('Angel One HTTP '+r.status+': '+txt.slice(0,240))}return {r,j}}
async function login(){const c=angelRuntime;if(!c.apiKey||!c.clientCode||!c.mpin)throw Error('Angel One API key, Client ID and MPIN are required');const totp=c.totpSecret?authenticator.generate(c.totpSecret):c.totp;if(!totp)throw Error('Current TOTP required');const {r,j}=await angelJson(A+'/rest/auth/angelbroking/user/v1/loginByPassword',{method:'POST',body:JSON.stringify({clientcode:c.clientCode,password:c.mpin,totp})});if(!j.status)throw Error(j.message||j.errorcode||('Angel login failed (HTTP '+r.status+')'));if(!j.data?.jwtToken)throw Error('Angel login succeeded without JWT token');sess={jwt:j.data.jwtToken,feed:j.data.feedToken,t:Date.now()};return sess}
async function ensureSession(){if(!sess||Date.now()-sess.t>3.5*3600000)return login();return sess}
async function quote(t){await ensureSession();let {j}=await angelJson(A+'/rest/secure/angelbroking/market/v1/quote/',{method:'POST',headers:{Authorization:'Bearer '+sess.jwt},body:JSON.stringify({mode:'FULL',exchangeTokens:t})});if(!j.status){sess=null;await ensureSession();({j}=await angelJson(A+'/rest/secure/angelbroking/market/v1/quote/',{method:'POST',headers:{Authorization:'Bearer '+sess.jwt},body:JSON.stringify({mode:'FULL',exchangeTokens:t})}))}if(!j.status)throw Error(j.message||'quote failed');return j.data?.fetched||[]}
function em(s){let m=/^(\\d{1,2})([A-Z]{3})(\\d{4})$/.exec(s||'');return m?Date.UTC(+m[3],['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC'].indexOf(m[2]),+m[1]):0}
async function sm(){if(master)return master;const f=path.join(__dirname,'tokens-cache.json');try{let c=JSON.parse(fs.readFileSync(f));if(c.d===new Date().toISOString().slice(0,10))return master=c.m}catch{}const r=await fetch('https://margincalculator.angelone.in/OpenAPI_File/files/OpenAPIScripMaster.json');if(!r.ok)throw Error('Scrip master failed');const a=await r.json(),eq={},op=[];for(const x of a){if(x.exch_seg==='NSE'&&x.symbol===x.name+'-EQ')eq[x.name]=x.token;if((x.exch_seg==='NFO'||x.exch_seg==='BFO')&&x.instrumenttype==='OPTIDX')op.push(x)}master={eq,op};try{fs.writeFileSync(f,JSON.stringify({d:new Date().toISOString().slice(0,10),m:master}))}catch{}return master}
function sendLive(obj){const data='data: '+JSON.stringify(obj)+'\\n\\n';for(const res of liveClients)try{res.write(data)}catch{}}
function parseTick(raw){const b=Buffer.from(raw);if(b.length<51)return null;const mode=b.readUInt8(0),ex=b.readUInt8(1),token=b.subarray(2,27).toString('utf8').replace(/\\0/g,'');const ltp=Number(b.readBigInt64LE(43))/100;return {token,exchangeType:ex,mode,ltp,ts:b.length>=43?Number(b.readBigInt64LE(35)):Date.now()}}
function sendSubscriptions(){if(!liveSocket||liveSocket.readyState!==WebSocket.OPEN)return;for(const v of Object.values(liveWanted)){if(!v.tokens.length)continue;for(let i=0;i<v.tokens.length;i+=1000)liveSocket.send(JSON.stringify({correlationID:'algodesk01',action:1,params:{mode:String(v.mode||1),tokenList:[{exchangeType:Number(v.ex),tokens:v.tokens.slice(i,i+1000)}]}}))}}
async function ensureLive(){if(liveSocket&&liveSocket.readyState===WebSocket.OPEN)return;if(liveConnecting)return;liveConnecting=true;try{await ensureSession();liveSocket=new WebSocket(WSURL,{headers:{Authorization:'Bearer '+sess.jwt,'x-api-key':angelRuntime.apiKey,'x-client-code':angelRuntime.clientCode,'x-feed-token':sess.feed}});liveSocket.on('open',()=>{liveConnecting=false;sendSubscriptions();sendLive({type:'status',live:true,time:new Date().toISOString()})});liveSocket.on('message',m=>{if(typeof m==='string')return;const t=parseTick(m);if(t){liveLast[t.token]=t;sendLive({type:'tick',...t})}});liveSocket.on('error',err=>sendLive({type:'status',live:false,error:err.message}));liveSocket.on('close',()=>{liveSocket=null;liveConnecting=false;sendLive({type:'status',live:false});setTimeout(()=>ensureLive().catch(()=>{}),5000)})}catch(x){liveConnecting=false;sendLive({type:'status',live:false,error:x.message})}}
setInterval(()=>{if(liveSocket?.readyState===WebSocket.OPEN)liveSocket.send('ping')},30000);
function want(ex,tokens,mode){const key=String(ex);liveWanted[key]??={ex,mode,tokens:[]};liveWanted[key].mode=mode;liveWanted[key].tokens=[...new Set([...liveWanted[key].tokens,...tokens.map(String)])];if(liveSocket?.readyState===WebSocket.OPEN)sendSubscriptions();ensureLive().catch(()=>{})}
for(const [n,[ex,t]] of Object.entries(IDX))want(ex==='NSE'?1:3,[t],1);

e.post('/api/angel/login',async(q,s)=>{try{const b=q.body||{};if(!b.clientCode||!b.mpin||!b.totp)throw Error('Client ID, MPIN and current TOTP are required');if(b.apiKey)angelRuntime.apiKey=String(b.apiKey);angelRuntime.clientCode=String(b.clientCode);angelRuntime.mpin=String(b.mpin);angelRuntime.totp=String(b.totp);angelRuntime.totpSecret='';sess=null;await login();await ensureLive();s.json({ok:true,connected:true,websocket:!!(liveSocket&&liveSocket.readyState===WebSocket.OPEN),message:'Angel One SmartAPI session established'})}catch(x){s.status(502).json({ok:false,error:x.message})}});
e.get('/api/angel/status',(q,s)=>s.json({configured:!!(angelRuntime.apiKey&&angelRuntime.clientCode&&angelRuntime.mpin),apiKeyConfigured:!!angelRuntime.apiKey,publicIpConfigured:!!ANGEL_CLIENT_PUBLIC_IP,session:!!sess,websocket:!!(liveSocket&&liveSocket.readyState===WebSocket.OPEN),clientCode:angelRuntime.clientCode?angelRuntime.clientCode.slice(0,3)+'***':''}));
e.post('/api/angel/test',async(q,s)=>{try{await ensureSession();const j=await quote({NSE:['99926000']});const x=j[0];s.json({ok:true,connected:true,websocket:!!(liveSocket&&liveSocket.readyState===WebSocket.OPEN),token:x?.symbolToken||'99926000',ltp:x?.ltp??null,time:new Date().toISOString()})}catch(x){sess=null;s.status(502).json({ok:false,error:x.message})}});
e.get('/api/health',(q,s)=>s.json({ok:true,angel:!!(angelRuntime.apiKey&&angelRuntime.clientCode&&angelRuntime.mpin),angelPublicIpConfigured:!!ANGEL_CLIENT_PUBLIC_IP,websocket:!!liveSocket&&liveSocket.readyState===WebSocket.OPEN,ai:!!ANTHROPIC_API_KEY,search:!!BRAVE_API_KEY}));
e.get('/api/live',(q,s)=>{s.setHeader('Content-Type','text/event-stream');s.setHeader('Cache-Control','no-cache');s.setHeader('Connection','keep-alive');s.flushHeaders?.();liveClients.add(s);s.write('data: '+JSON.stringify({type:'status',live:!!liveSocket&&liveSocket.readyState===WebSocket.OPEN,time:new Date().toISOString()})+'\\n\\n');Object.values(liveLast).slice(-200).forEach(t=>s.write('data: '+JSON.stringify({type:'tick',...t})+'\\n\\n'));q.on('close',()=>liveClients.delete(s));ensureLive().catch(()=>{})});
e.use(express.static(path.join(__dirname,'../www')));e.get('*',(q,s)=>s.sendFile(path.join(__dirname,'../www/index.html')));
e.listen(PORT,()=>console.log('AlgoDesk Pro server on '+PORT));
