require('dotenv').config();
const express=require('express'),cors=require('cors'),dns=require('dns').promises,net=require('net');
const {authenticator}=require('otplib');
const {classifyOI,calcPCR,findSupportResistance,expectedValue,isVerifiedSignal}=require('./lib/analytics');

const PORT=Number(process.env.PORT||8787);
const {ANTHROPIC_API_KEY,BRAVE_API_KEY,APP_KEY,ANGEL_API_KEY,ANGEL_CLIENT_CODE,ANGEL_PIN,ANGEL_TOTP_SECRET,MODEL='claude-haiku-4-5-20251001'}=process.env;
const app=express();app.set('trust proxy',1);app.use(cors());app.use(express.json({limit:'8mb'}));

const hits=new Map(),heavyHits=new Map();
function limiter(store,max){return(req,res,next)=>{const now=Date.now(),key=req.ip,list=(store.get(key)||[]).filter(t=>now-t<60000);list.push(now);store.set(key,list);if(list.length>max)return res.status(429).json({error:'bahut zyada requests, thodi der baad try karo'});next()}}
app.use('/api',(req,res,next)=>{if(APP_KEY&&req.get('x-app-key')!==APP_KEY)return res.status(401).json({error:'unauthorized'});next()},limiter(hits,120));
const heavy=limiter(heavyHits,15);

app.get('/api/health',(_req,res)=>res.json({ok:true,build:'algodesk-fresh',readOnly:true,ai:!!ANTHROPIC_API_KEY,search:!!BRAVE_API_KEY,angel:!!(ANGEL_API_KEY&&ANGEL_CLIENT_CODE&&ANGEL_PIN&&ANGEL_TOTP_SECRET),signalRule:{minWinRatePct:80,minTrades:100}}));

async function claude(messages,images=[],max_tokens=700){
 if(!ANTHROPIC_API_KEY)throw new Error('ANTHROPIC_API_KEY set nahi hai');
 const normalized=messages.map(m=>({role:m.role,content:m.content}));
 if(images.length){const last=normalized[normalized.length-1];last.content=[...images.map(i=>({type:'image',source:{type:'base64',media_type:i.media_type,data:i.data}})),{type:'text',text:String(last.content)}]}
 const r=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'content-type':'application/json','x-api-key':ANTHROPIC_API_KEY,'anthropic-version':'2023-06-01'},body:JSON.stringify({model:MODEL,max_tokens,messages:normalized})});
 const j=await r.json();if(!r.ok)throw new Error(j?.error?.message||'Anthropic HTTP '+r.status);
 return{text:(j.content||[]).filter(x=>x.type==='text').map(x=>x.text).join(''),truncated:j.stop_reason==='max_tokens'};
}
app.post('/api/ai',heavy,async(req,res)=>{try{const{messages,images=[]}=req.body||{};if(!Array.isArray(messages)||!messages.length||messages.length>12)return res.status(400).json({error:'messages galat'});if(messages[0].role!=='user'||messages[messages.length-1].role!=='user')return res.status(400).json({error:'message roles galat'});for(const m of messages)if(!['user','assistant'].includes(m.role)||typeof m.content!=='string'||!m.content||m.content.length>20000)return res.status(400).json({error:'message galat'});if(!Array.isArray(images)||images.length>3||images.some(i=>!['image/jpeg','image/png','image/webp'].includes(i.media_type)||typeof i.data!=='string'||i.data.length>6000000))return res.status(400).json({error:'image galat'});res.json(await claude(messages,images))}catch(e){res.status(502).json({error:e.message})}});

async function braveSearch(q,count=8){if(!BRAVE_API_KEY)throw new Error('BRAVE_API_KEY set nahi hai');const r=await fetch('https://api.search.brave.com/res/v1/web/search?count='+count+'&q='+encodeURIComponent(q),{headers:{'X-Subscription-Token':BRAVE_API_KEY,accept:'application/json'}}),j=await r.json();if(!r.ok)throw new Error('Search HTTP '+r.status);return(j?.web?.results||[]).map(x=>({title:x.title,url:x.url,desc:String(x.description||'').replace(/<[^>]+>/g,'')}))}
app.get('/api/search',heavy,async(req,res)=>{try{const q=String(req.query.q||'').trim().slice(0,200);if(!q)return res.status(400).json({error:'q khaali hai'});res.json({results:await braveSearch(q)})}catch(e){res.status(502).json({error:e.message})}});

function privateIp(ip){if(net.isIPv4(ip)){const[a,b]=ip.split('.').map(Number);return a===0||a===10||a===127||(a===169&&b===254)||(a===172&&b>=16&&b<=31)||(a===192&&b===168)||(a===100&&b>=64&&b<=127)}const s=ip.toLowerCase();return s==='::1'||s==='::'||s.startsWith('fc')||s.startsWith('fd')||s.startsWith('fe80')||s.startsWith('::ffff:')}
async function fetchSafe(url,depth=0){const u=new URL(url);if(!['http:','https:'].includes(u.protocol))throw new Error('sirf http/https link chalega');const addrs=await dns.lookup(u.hostname,{all:true});if(addrs.some(a=>privateIp(a.address)))throw new Error('ye address allowed nahi');const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),8000);try{const r=await fetch(u,{signal:ctl.signal,redirect:'manual',headers:{'user-agent':'AlgoDeskBot/1.0',accept:'text/html,text/plain;q=0.9'}});if(r.status>=300&&r.status<400&&r.headers.get('location')){if(depth>=3)throw new Error('bahut redirects');return fetchSafe(new URL(r.headers.get('location'),u).href,depth+1)}if(!r.ok)throw new Error('HTTP '+r.status);return Buffer.from(await r.arrayBuffer()).subarray(0,1500000).toString('utf8')}finally{clearTimeout(timer)}}
const textOf=h=>h.replace(/<(script|style|noscript|svg)[\s\S]*?<\/\1>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/\s+/g,' ').trim().slice(0,5000);
const WEB_RULES='सिर्फ दिए गए public page data के आधार पर सरल हिंदी में जवाब दो। कोई खबर या आंकड़ा मत गढ़ो। पुराना/अधूरा data साफ कहो। मुनाफे की गारंटी या buy/sell instruction मत दो। 150 शब्दों के भीतर पाँच headings रखो: क्या हो रहा है:, पॉज़िटिव:, नेगेटिव:, दिक्कत / रिस्क:, अब क्या देखें:';
app.post('/api/webask',heavy,async(req,res)=>{try{const q=String(req.body?.q||'').trim().slice(0,200),url=String(req.body?.url||'').trim();if(!q&&!url)return res.status(400).json({error:'q ya url do'});let pages;if(url)pages=[{url,text:textOf(await fetchSafe(url))}];else{const rs=await braveSearch(q,5),got=await Promise.allSettled(rs.slice(0,3).map(async r=>({url:r.url,text:textOf(await fetchSafe(r.url))})));pages=got.filter(x=>x.status==='fulfilled').map(x=>x.value);if(!pages.length)pages=rs.slice(0,3).map(r=>({url:r.url,text:r.title+'. '+r.desc}))}if(!pages.length)return res.status(404).json({error:'कोई पेज नहीं मिला'});const ctx=pages.map((p,i)=>'[पेज '+(i+1)+'] '+p.url+'\n'+p.text).join('\n\n');const out=await claude([{role:'user',content:WEB_RULES+'\n\nसवाल: '+(q||'इस page का data समझाओ')+'\n\n'+ctx}],[],800);res.json({text:out.text,sources:pages.map(p=>p.url)})}catch(e){res.status(502).json({error:e.message})}});

const ANGEL='https://apiconnect.angelbroking.com',IDX_TOK={'NIFTY 50':['NSE','99926000'],BANKNIFTY:['NSE','99926009'],FINNIFTY:['NSE','99926037'],MIDCPNIFTY:['NSE','99926074'],SENSEX:['BSE','99919000']},STOCKS=['RELIANCE','HDFCBANK','SBIN','TATAMOTORS','INFY','ICICIBANK','TCS','BAJFINANCE','ITC','LT'];
let session=null,master=null,cache=null;
const h=extra=>({'Content-Type':'application/json',Accept:'application/json','X-UserType':'USER','X-SourceID':'WEB','X-ClientLocalIP':'127.0.0.1','X-ClientPublicIP':'127.0.0.1','X-MACAddress':'00:00:00:00:00:00','X-PrivateKey':ANGEL_API_KEY,...extra});
async function angelLogin(){if(!(ANGEL_API_KEY&&ANGEL_CLIENT_CODE&&ANGEL_PIN&&ANGEL_TOTP_SECRET))throw new Error('Angel One env set nahi hain');const r=await fetch(ANGEL+'/rest/auth/angelbroking/user/v1/loginByPassword',{method:'POST',headers:h(),body:JSON.stringify({clientcode:ANGEL_CLIENT_CODE,password:ANGEL_PIN,totp:authenticator.generate(ANGEL_TOTP_SECRET)})}),j=await r.json();if(!j.status)throw new Error('Angel login: '+(j.message||r.status));session={jwt:j.data.jwtToken,at:Date.now()}}
async function loadMaster(){if(master)return master;const r=await fetch('https://margincalculator.angelbroking.com/OpenAPI_File/files/OpenAPIScripMaster.json');if(!r.ok)throw new Error('ScripMaster HTTP '+r.status);const rows=await r.json(),eq={};for(const x of rows)if(x.exch_seg==='NSE'&&STOCKS.includes(x.name)&&x.symbol===x.name+'-EQ')eq[x.name]=x.token;return master={eq}}
async function angelQuote(tokens){const call=()=>fetch(ANGEL+'/rest/secure/angelbroking/market/v1/quote/',{method:'POST',headers:h({Authorization:'Bearer '+session.jwt}),body:JSON.stringify({mode:'FULL',exchangeTokens:tokens})}).then(r=>r.json());if(!session||Date.now()-session.at>21600000)await angelLogin();let j=await call();if(!j.status){await angelLogin();j=await call()}if(!j.status)throw new Error('Angel quote: '+(j.message||'fail'));return j.data?.fetched||[]}
async function getQuotes(){if(cache&&Date.now()-cache.ts<1500)return cache;const m=await loadMaster(),ex={NSE:[],BSE:[]};Object.values(IDX_TOK).forEach(([e,t])=>ex[e].push(t));STOCKS.forEach(s=>{if(m.eq[s])ex.NSE.push(m.eq[s])});const rows=await angelQuote(ex),by={};rows.forEach(r=>by[r.exchange+':'+r.symbolToken]=r);const indices=Object.entries(IDX_TOK).map(([n,[e,t]])=>{const r=by[e+':'+t];return r?{n,p:r.ltp,chg:r.percentChange}:null}).filter(Boolean);const stocks=STOCKS.map(s=>{const r=by['NSE:'+m.eq[s]];return r?{s,p:r.ltp,chg:r.percentChange,oiChg:null}:null}).filter(Boolean);return cache={indices,stocks,ts:Date.now(),note:'OI change needs timestamped intraday snapshots; n/a until that history is available'}}
app.get('/api/quotes',async(_req,res)=>{try{res.json(await getQuotes())}catch(e){res.status(503).json({error:e.message})}});
app.listen(PORT,()=>console.log('AlgoDesk fresh server listening on '+PORT));
