require('dotenv').config();
const express=require('express'),cors=require('cors'),{authenticator}=require('otplib'),fs=require('fs'),path=require('path');
const e=express();e.use(cors());e.use(express.json({limit:'8mb'}));
const {PORT=8787,APP_KEY,ANGEL_API_KEY,ANGEL_CLIENT_CODE,ANGEL_PIN,ANGEL_TOTP_SECRET,ANTHROPIC_API_KEY,MODEL='claude-haiku-4-5-20251001',BRAVE_API_KEY}=process.env;
const A='https://apiconnect.angelbroking.com',IDX={'NIFTY 50':['NSE','99926000'],'BANKNIFTY':['NSE','99926009'],'FINNIFTY':['NSE','99926037'],'MIDCPNIFTY':['NSE','99926074'],'SENSEX':['BSE','99919000']};
let sess=null,master=null;
e.use('/api',(q,s,n)=>{if(APP_KEY&&q.get('x-app-key')!==APP_KEY)return s.status(401).json({error:'unauthorized'});n()});
const hd=x=>({'Content-Type':'application/json','X-UserType':'USER','X-SourceID':'WEB','X-ClientLocalIP':'127.0.0.1','X-ClientPublicIP':'127.0.0.1','X-MACAddress':'00:00:00:00:00:00','X-PrivateKey':ANGEL_API_KEY,...x});
async function login(){if(!ANGEL_API_KEY||!ANGEL_CLIENT_CODE||!ANGEL_PIN||!ANGEL_TOTP_SECRET)throw Error('Angel One credentials not configured');const r=await fetch(A+'/rest/auth/angelbroking/user/v1/loginByPassword',{method:'POST',headers:hd(),body:JSON.stringify({clientcode:ANGEL_CLIENT_CODE,password:ANGEL_PIN,totp:authenticator.generate(ANGEL_TOTP_SECRET)})}),j=await r.json();if(!j.status)throw Error(j.message||'Angel login failed');sess={jwt:j.data.jwtToken,t:Date.now()}}
async function quote(t){if(!sess||Date.now()-sess.t>5*3600000)await login();let r=await fetch(A+'/rest/secure/angelbroking/market/v1/quote/',{method:'POST',headers:hd({Authorization:'Bearer '+sess.jwt}),body:JSON.stringify({mode:'FULL',exchangeTokens:t})}),j=await r.json();if(!j.status){await login();r=await fetch(A+'/rest/secure/angelbroking/market/v1/quote/',{method:'POST',headers:hd({Authorization:'Bearer '+sess.jwt}),body:JSON.stringify({mode:'FULL',exchangeTokens:t})});j=await r.json()}if(!j.status)throw Error(j.message||'quote failed');return j.data?.fetched||[]}
function em(s){let m=/^(\\d{1,2})([A-Z]{3})(\\d{4})$/.exec(s||'');return m?Date.UTC(+m[3],['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC'].indexOf(m[2]),+m[1]):0}
async function sm(){if(master)return master;const f=path.join(__dirname,'tokens-cache.json');try{let c=JSON.parse(fs.readFileSync(f));if(c.d===new Date().toISOString().slice(0,10))return master=c.m}catch{}const r=await fetch('https://margincalculator.angelbroking.com/OpenAPI_File/files/OpenAPIScripMaster.json');if(!r.ok)throw Error('Scrip master failed');const a=await r.json(),eq={},op=[];for(const x of a){if(x.exch_seg==='NSE'&&x.symbol===x.name+'-EQ')eq[x.name]=x.token;if((x.exch_seg==='NFO'||x.exch_seg==='BFO')&&x.instrumenttype==='OPTIDX')op.push(x)}master={eq,op};try{fs.writeFileSync(f,JSON.stringify({d:new Date().toISOString().slice(0,10),m:master}))}catch{}return master}
e.get('/api/health',(q,s)=>s.json({ok:true,angel:!!(ANGEL_API_KEY&&ANGEL_CLIENT_CODE&&ANGEL_PIN&&ANGEL_TOTP_SECRET),ai:!!ANTHROPIC_API_KEY,search:!!BRAVE_API_KEY}));
e.get('/api/quotes',async(q,s)=>{try{let t={NSE:Object.values(IDX).filter(x=>x[0]==='NSE').map(x=>x[1]),BSE:[IDX.SENSEX[1]]};let m=await sm();t.NSE=t.NSE.concat(Object.values(m.eq).slice(0,20));let f=await quote(t),b={};f.forEach(x=>b[x.symbolToken||x.token]=x);s.json({live:true,indices:Object.entries(IDX).map(([n,x])=>({n,p:+(b[x[1]]?.ltp||0),chg:+(b[x[1]]?.percentChange||0)})),stocks:Object.entries(m.eq).slice(0,20).map(([n,t])=>({s:n,p:+(b[t]?.ltp||0),chg:+(b[t]?.percentChange||0),oiChg:null})),time:new Date().toISOString()})}catch(x){s.status(502).json({live:false,error:x.message})}});
e.get('/api/option-chain',async(q,s)=>{try{let name=(q.query.index||'NIFTY').toUpperCase().replace('NIFTY 50','NIFTY'),m=await sm(),a=m.op.filter(x=>x.name===name&&em(x.expiry)>=Date.now()).sort((x,y)=>em(x.expiry)-em(y.expiry)),exp=a[0]?.expiry,cs=a.filter(x=>x.expiry===exp);if(!cs.length)throw Error('contracts not found');let spotTok=(IDX[name==='NIFTY'?'NIFTY 50':name]||IDX['NIFTY 50'])[1],spotEx=(name==='SENSEX'?'BSE':'NSE'),sp=(await quote({[spotEx]:[spotTok]}))[0]?.ltp||0;cs=cs.map(x=>({...x,d:Math.abs(+x.strike-sp)})).sort((x,y)=>x.d-y.d).slice(0,24);let byEx={};cs.forEach(x=>(byEx[x.exch_seg]??=[]).push(x.token));let qs=[];for(const [ex,t] of Object.entries(byEx))for(let i=0;i<t.length;i+=45)qs.push(...await quote({[ex]:t.slice(i,i+45)}));let b={};qs.forEach(x=>b[x.symbolToken||x.token]=x);let rows=[];for(const x of cs){let r=rows.find(z=>z.strike==+x.strike);if(!r)rows.push(r={strike:+x.strike,ce:null,pe:null});r[x.symbol.endsWith('CE')?'ce':'pe']={ltp:+(b[x.token]?.ltp||0),oi:+(b[x.token]?.opnInterest||b[x.token]?.openInterest||0),symbol:x.symbol}}rows.sort((a,b)=>a.strike-b.strike);let co=rows.reduce((n,r)=>n+(r.ce?.oi||0),0),po=rows.reduce((n,r)=>n+(r.pe?.oi||0),0);s.json({live:true,index:name,expiry:exp,atm:+sp,pcr:po/Math.max(1,co),rows})}catch(x){s.status(502).json({live:false,error:x.message})}});
async function ai(txt){if(!ANTHROPIC_API_KEY)throw Error('AI key missing');let r=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'content-type':'application/json','x-api-key':ANTHROPIC_API_KEY,'anthropic-version':'2023-06-01'},body:JSON.stringify({model:MODEL,max_tokens:600,messages:[{role:'user',content:'सिर्फ दिए data पर सरल Hindi में जवाब दो। कोई data/news मत गढ़ो। Buy/Sell/order instruction या profit guarantee नहीं। 120 शब्द के अंदर पाँच headings: क्या हो रहा है:, पॉज़िटिव ✅:, नेगेटिव ❌:, दिक्कत / रिस्क ⚠️:, अब क्या देखें 👀:\n\n'+txt}]})}),j=await r.json();if(!r.ok)throw Error(j.error?.message||'AI failed');return j.content?.map(x=>x.text||'').join('')}
e.post('/api/ai',async(q,s)=>{try{s.json({text:await ai(JSON.stringify(q.body||{}))})}catch(x){s.status(502).json({error:x.message})}});
e.get('/api/search',async(q,s)=>{try{if(!BRAVE_API_KEY)throw Error('Search key missing');let z=await fetch('https://api.search.brave.com/res/v1/web/search?count=8&q='+encodeURIComponent(q.query||''),{headers:{'X-Subscription-Token':BRAVE_API_KEY,Accept:'application/json'}}),j=await z.json();s.json({results:(j.web?.results||[]).map(x=>({title:x.title,url:x.url,desc:x.description||''}))})}catch(x){s.status(502).json({error:x.message})}});
e.listen(PORT,()=>console.log('AlgoDesk Pro server '+PORT));